# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
